/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:0ab7b280-7f25-4770-bb76-c585b05204cb",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_OOhZLG9VD",
    "aws_user_pools_web_client_id": "4s7qsve1o63f23u55l5ulv4soa",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://t3lern6eczberefiucuykxkliu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-osalfibn2zdtpp47byakr3li7a"
};


export default awsmobile;
