/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:37d9d34f-5ef7-4c08-81fc-45a1f01c1de1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_o6ERDUTPH",
    "aws_user_pools_web_client_id": "auprs5ttm7bficuk264f339gj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://t3lern6eczberefiucuykxkliu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-osalfibn2zdtpp47byakr3li7a",
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "managers-dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
